name: build+push-docker-image
on: [push]
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - name: install homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: install docker
      run: brew install docker
    - name: install tree
      run: brew install tree
    - name: find docker daemon
      run: |
        ls -alsh /usr/local/Cellar/docker/26.0.2
        tree /usr/local/Cellar/docker
    - name : start docker daemon
      run: dockerd
    - name: build
      run: docker build -t ${{ github.repository }}:${{ github.sha }} .
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Tag Docker image
      run: docker tag ${{ github.repository }}:${{ github.sha }} ${{ github.repository }}:latest
    - name: Push Docker image
      run: |
        docker push ${{ github.repository }}:${{ github.sha }}
        docker push ${{ github.repository }}:latest
        
